spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/beyondyanyi/spring-cloud-config
          search-paths: /
          username: yanyiyanyi@163.com
          password: yanyi961201

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

foo: 1212